// {
//     "email": "afeezalamu527@gmail.com",
//     "password": "Afeez527@gmail.com"
//   }

// products testing
// {
//     "title": "Iphone 13",
//     "price": 800,
//     "description": "Clean and sharp phone",
//     "image": "https://example.com/image.jpg",
//     "countInStock": 5
//   }


// cart testing
// {
//     "productId": "507f1f77bcf86cd799439011",
//     "quantity": 2
//   }



// {
//     "username": "Feezy",
//     "email": "afeezalamu527@gmail.com",
//     "password": "oGtrXf1HgKylIySe",
//     "isAdmin": true
//   }



// {
//     "name": "Olamide",
//     "email": "john251@gmail.com",
//     "password": "Ola527",
//     "isAdmin": true
//   }



// {
//     "_id": "69d3604842e8881589bfedd0",
//     "name": "Olamide",
//     "email": "john251@gmail.com",
//     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDM2MDQ4NDJlODg4MTU4OWJmZWRkMCIsImlhdCI6MTc3NTQ2MTE1MywiZXhwIjoxNzc4MDUzMTUzfQ.4GOyIjYPuqZ8HAIQ7PxsbxZ0gWgBezIENJ-TlsXJKJQ"
//   }